# Generated by Django 3.0.3 on 2020-04-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='UserProgress',
        ),
    ]
