# Generated by Django 3.0.3 on 2020-04-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200408_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
                ('mags', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserProgress')),
            ],
        ),
    ]
