# Generated by Django 3.0.3 on 2020-04-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dormitory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='mags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mags', to='api.UserProgress'),
            preserve_default=False,
        ),
    ]
