# Generated by Django 3.0.3 on 2020-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200427_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='magicscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
