# Generated by Django 3.0.3 on 2020-06-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200605_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
